[package]
name = "graphics-playground-rs"
version = "0.1.0"
authors = ["Chris Rice <chris@chrisrice.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
